### ISSUE TITLE
Windows crlf

### ISSUE THREAD

**Issue by gitfoxi** [AccelerationNet/cl-csv#21]
(cl-csv:read-csv (make-string-input-stream (format nil "a~C~Cb" #\Newline #\Linefeed)))

    (("a") ("") ("b"))

**Comment by bobbysmith007** [comment]
There are many options for the parser available and the parser has been successfully used against many different "csvish streams".

Here is how to make this work (using cl-interpol for terseness):
(cl-csv:read-csv (make-string-input-stream #?"a\r\nb") :newline #?"\r\n")

**Comment by gitfoxi** [comment]
That's good but it doesn't address that a csv may come from anywhere and you might not want to have to care about detecting line-ending format. I find that using `uiop:read-file-string` to pre-read the file helps, but there's a case that even that doesn't cover which is excel for mac sometimes saves a csv using only #\Return to separate lines.

**Comment by bobbysmith007** [comment]
The better solution is to determine the line ending first and then use that line ending.  We dont wish to read the whole file in (because that could be very large).  I wrote a basic read-any-line function that would operate as you suggest, but its about 7x slower than the standard read-line or the read-until (.1 to .7 sec) function that are currently being used (depending on line ending).  While this is acceptable for some workloads, I dont want to add a 7x slowdown in performance for very little gain.  I will see if I can come up with something else that works, but this is not a priority.  

Patches are of course welcome provided that they maintain backward compatibility, and roughly the same performance for the cases currently used.

Cheers, and thanks for your interest in this library

**Comment by rolfmblindgren** [comment]
I'm trying to read csv data exported from FileMaker for Mac.

It seems read-csv does not recognize any line ending formats. Inspecting the input file, it seems that #\Return should be the right line ending. But that gives

```
Array index -1 out of bounds for "" .
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT-BREAK] Reset this thread
 3: [ABORT] Kill this thread

Backtrace:
  0: (CCL::SET-FILL-POINTER "" -1)
  1: ((:INTERNAL CL-CSV::READ-LINE-IF-NEEDED CL-CSV::BODY CL-CSV:READ-CSV-ROW))
  2: ((:INTERNAL CL-CSV::NEXT-CHAR CL-CSV::BODY CL-CSV:READ-CSV-ROW))
  3: ((:INTERNAL CL-CSV::BODY CL-CSV:READ-CSV-ROW))
  4: (CL-CSV:READ-CSV-ROW #P"/Users/roffe/Documents/big5/Big5.csv" :SEPARATOR #\Tab :QUOTE #\" :ESCAPE "\"\"" :UNQUOTED-EMPTY-STRING-IS-NIL NIL :QUOTED-EMPTY-STRING-IS-NIL NIL :TRIM-OUTER-WHITESPACE T :NEW..
  5: (CCL::CALL-CHECK-REGS CL-CSV:READ-CSV-ROW #P"/Users/roffe/Documents/big5/Big5.csv" :NEWLINE #\Return :SEPARATOR #\Tab)
  6: (CCL::CHEAP-EVAL (CL-CSV:READ-CSV-ROW *DATABASE-FILE* :NEWLINE #\Return :SEPARATOR #\Tab))
 --more--
```

#\cr or "#\cr#\lf" runs, but the result is just one long list.

Any suggestions?

**Comment by bobbysmith007** [comment]
Hrmm... I *thought* there was a test case for this, but its been a while since i had to work on this library.  I will look into this.

**Comment by bobbysmith007** [comment]
I cant reproduce this on my end.  I added a couple of assertions to the "different-newlines" test in the test suite.  
 * What version are you using?  
 * Is it fresh from quicklisp?  
 * Do all the tests pass on your implementation?   `(run-all-tests)` in the test package should pretty much show whats working and whats not.

This test case uses cl-interpol so that the \r can be easily inserted in this comment, but it seems to work no matter how I encode \r :
```
(with-input-from-string (in #?"a|b|c|d\r1|2|3|4")
    (let ((rows (cl-csv:read-csv in :newline #\Return :separator "|")))
      (assert-equal 2 (length rows))
      (assert-equal '("a" "b" "c" "d") (first rows))
      (assert-equal '("1" "2" "3" "4") (second rows)))
    )
```

You could also try attaching a small reproduction file to the ticket so that I can try running directly against your data.

**Comment by bobbysmith007** [comment]
This ticket along with one about more flexible separators had me have a go at rewriting the parser.
#24 

Without using any tricks or optimizations, but with a more interesting design choice I was able to both improve readability, reduce interdependencies and closed variables, as well as improve performance slightly (not sure how I arranged that!).

While its not quite where I want it to be, it is far enough along and seems to be passing the test suite well enough, that you may wish to check it out. I will be pushing it up here momentarily.

@rolfmblindgren  I havn't heard back, and I believe both the old variant and new variants are correctly working if you specify #\return as the line ending
