### ISSUE TITLE
Missing fields at end-of-line

### ISSUE THREAD

**Issue by gitfoxi** [AccelerationNet/cl-csv#22]
(cl-csv:read-csv (make-string-input-stream (format nil "a,b~%1,2~%1~%1,2")))

    (("a" "b") ("1" "2") ("1") ("1" "2"))

I would desire that missing fields get filled with `nil`. For example:

    (("a" "b") ("1" "2") ("1",nil) ("1" "2"))

**Comment by bobbysmith007** [comment]
1) It is filled in with null basically: `(nth 2 '("1")) => nil`,

2) The parser is not stateful enough to know there are supposed to be "n" columns, so without passing a new input parameter specifying row length, there is not really a way (what if the very last row contains 2 additional columns).  CL-CSV supports per row handling so that you can stream the results of VERY large csvs without bringing them entirely into memory so there is intended to be no statefulness between rows.  

3) Additionally this can be added as a function call on the results trivially if necessary.

4) Look into data-tables, which has a function to even out the rows, can perform all sorts of data-access and manipulations on the results, will automatically try to convert types to the correct common lisp types if you want etc.  Basically this already contains the piece you want, and alternatively provides access functions that are row length agnostic (like nth)

Cheers,
I hope you find cl-csv useful
